### ISSUE TITLE
Regional MediaPackage sync

### ISSUE THREAD

**Issue by OrenMe** [awslabs/aws-stale-playlist-detector#29]
How do you keep the two separate regions in sync?
I assume having the top master playlist contain redundant streams means that they are aligned in timestamp and segment numbers.

**Comment by JimTharioAmazon** [comment]
Hi,

Yes, you are correct. The streams need to be in sync. The delivery, number of synchronized streams and the type of origin used to deliver those streams is outside of the scope of this solution since there could be many options someone implementing this solution can choose. The examples here reference MediaPackage, but it could be MediaStore, or another live origin product.

The two main capabilities offered by this solution include:

1. A container-based monitoring tool (stale playlist detector) that detects when a specific origin playlist stops changing and provides signaling to human or automated systems to react to that situation.

2.  L@E functions that are installed into multiple CloudFront distributions (based on the number of redundant streams) that can be remotely controlled to quickly cut-off distributions connected to problematic origins. When activated these CloudFront distributions return 404 for every request and force the client player to an alternate stream.

**Comment by OrenMe** [comment]
Thanks @JimTharioAmazon
